(ns cadence.views.landing
  (:require [cadence.views.common :as common])
  (:use noir.core
        hiccup.core
        hiccup.page-helpers))

(defpage root "/" []
  (common/layout
    [:div.page-header [:h1 "Welcome to Cadence!"]]
    [:container-fluid
     [:div.row-fluid
      [:div#faqs.span2
       [:h3 "Questions"]
       [:ul.nav.nav-stacked.nav-tabs
        [:li (link-to "#intro" "What is all this?")]
        [:li (link-to "#usage" "What should I do?")]
        [:li (link-to "#privacy" "Can I trust you?")]
        [:li (link-to "#secutiry" "Am I safe?")]]]
      [:div.span10
       [:h2#intro "A Quick Introduction"]
       [:p "Cadence is really two things, a web app and "
        (link-to "https://github.com/RyanMcG/Cadence-js" "Cadence.js")
        ". The latter is a jQuery plugin which is used to monitor user input
        style on a single input field. For more information on "
        (link-to "https://github.com/RyanMcG/Cadence-js" "Cadence.js")
        " check out the links in the navbar."]
       [:p "This web app is a demo/example usage of Cadence.js. There are
           several things you need to do to test it out.  First off, you need "
        "to " (link-to "/signup" "signup") " and "
        (link-to "/login" "login") "."]
       [:h2#usage "Using this site"]
       [:p "There are a few things you things you can do with cadence, but they
           all require making an account first. To signup for an account "
        (link-to "/signup" "click here")
        " or use the links in user-dropdown on the right side of the navbar. "
        "Once you've signup up and logged in you should be able to start
        training." ]
       [:div.well
        [:p#training [:strong "What is training? "]
         "Training is an essential part of using supervised learners.  This
         application takes the output from Cadence.js during training and uses
         it to create a model for Support Vector Machine classification."]
        [:div#authentication "During " [:strong "authentication"]
         " that classifier is called up and used on a new output from Cadence.js
         and determines whether that output is \"authenic\". Hopefully, for the
         classifier to consider the given cadence authentic it will have to be
         generated by whomever did the training in the first place."]]
       ]]]))
